### PR TITLE
Add queue_size=5 parameter to all publishers to avoid the WARN on Indigo

### PR DESCRIPTION
**Pull request by corot**
SyntaxWarning: The publisher should be created with an explicit keyword
argument 'queue_size'. Please see
http://wiki.ros.org/rospy/Overview/Publishers%20and%20Subscribers for
more information.

@mikeferguson, I add this to hydro-devel as we don't have still an indigo branch, but I have no problem doing otherwise, that is, create an indigo branch and add all oncoming changes there. Up to you!.

### CODE REVIEW

**Comment by mikeferguson** [comment]
Thanks! I've created an indigo-devel branch, please open a new PR to put these changes there.

**Comment by mikeferguson** [comment]
Actually, I just cherry-picked your commit. All set. Closed by 2237b32c2d89306efad83a06529f339c658099b6

**Comment by mikeferguson** [comment]
Released to indigo debs as 0.10.0

**Comment by corot** [comment]
Cool. I switch to indigo branch from now.

2014-07-14 23:41 GMT+02:00 Michael Ferguson notifications@github.com:

**Pull request closed without merging**
