### PR TITLE
Check if command exceeds opening limits also for single side controller.

### PR DESCRIPTION
**Pull request by corot**
Also, error fixed for the trapezoidal controller, as self.min/max_opening is not defined on TrapezoidGripperModel class

### CODE REVIEW

**Comment by mikeferguson** [comment]
LGTM

**Comment by corot** [comment]
Thanks.

As you see, I'm putting up to date the turtlebot arm related code. I have push permits on [turtlebot_arm](https://github.com/turtlebot/turtlebot_arm), but not for arbotix_ros, so I'll bother you a little bit more, sorry in advance.

Btw, I have modified the arbotix_firmware to work with the new Robotis OpenCM9.04 controller. It can interface now with the rest of arbotix_ros code (well, I only tried to control AX-12 motors and read analog ports). Would you like me to pull req it as a new package, say opencm_firmware? Or you prefer to keep arbotix_ros 100% ArbotiX-related?

**Comment by mikeferguson** [comment]
If you want to ping me with an @mikeferguson on future turtlebot_arm PRs, I can take a look at those and offer advice.

If you point me at the mods you've made for openCM, we might be able to just get them into the arbotix_firmware package. If we were going to create a new opencm_firmware, I'd suggest putting that into a new repository.

**Comment by corot** [comment]
Great. Thanks

For turtlebot_arm, I'll create a hydro (or maybe indigo) devel branch, so
no mangling with current version

For the openCM fimware, it's very different from the arbotix one, so no way
to do a compatible one. Or you mean put both .ino files in the arbotix_firmware
package?

2014-05-29 4:04 GMT+02:00 Michael Ferguson notifications@github.com:

**Pull request merged**
